specVersion: 0.2.0
name: acala-subql
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b'
  endpoint: wss://karura.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/AcalaNetwork/karura-dictionary
  chaintypes:
    file: './src/chain-types.js'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1516318
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: ProvisioningToEnabled
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: AddLiquidity
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: RemoveLiquidity
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: Swap
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: ListProvision
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: AddProvision
