specVersion: 0.2.0
name: acala-subql
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c'
  endpoint: wss://acala-polkadot.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/acala-dictionary
  chaintypes:
    file: './src/types.json'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1000000
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: ProvisioningToEnabled
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: AddLiquidity
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: RemoveLiquidity
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: Swap
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: ListProvision
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: dex
            method: AddProvision
